[install]
allowed_installtypes = ["wholedisk"]
copy_mode = "bootc"
bootc_imgref = "containers-storage:localhost/luminusos-workstation:latest"
bootc_target_imgref = "localhost/luminusos-workstation:latest"
bootc_enforce_sigpolicy = false
bootc_args = ["--skip-fetch-check", "--skip-finalize", "--bootupd-skip-boot-uuid"]

[distro]
name = "Luminus OS"
icon = "fedora-logo-icon"
bios_support = true

[[bento]]
title = "luminusos-bento-welcome"
desc = "luminusos-bento-welcome-desc"
link = "https://github.com/luminusOS"
icon = "explore-symbolic"

[[bento]]
title = "luminusos-bento-help"
desc = "luminusos-bento-help-desc"
link = "https://github.com/luminusOS/images/issues"
icon = "chat-symbolic"

[[bento]]
title = "luminusos-bento-contribute"
desc = "luminusos-bento-contribute-desc"
link = "https://github.com/luminusOS/images"
icon = "applications-development-symbolic"

[[postinstall]]
module = "Script"
