[Partition]
Type=root
Format=btrfs
MountPoint=/
CopyFiles=/:/
ExcludeFiles=/boot/
ExcludeFiles=/etc/readymade.toml
ExcludeFiles=/etc/gdm/custom.conf
ExcludeFiles=/etc/xdg/autostart/com.fyralabs.Readymade.desktop
ExcludeFiles=/etc/polkit-1/rules.d/49-luminusos-readymade.rules
ExcludeFiles=/etc/dconf/db/local
ExcludeFiles=/etc/dconf/db/local.d/00-luminusos-live
ExcludeFiles=/etc/dconf/profile/user
ExcludeFiles=/etc/systemd/user/gnome-session@live-installer.target.wants/luminusos-activate-aurora-shell.service
ExcludeFiles=/etc/systemd/user/gnome-session@live-installer.target.wants/luminusos-enable-aurora-shell.service
ExcludeFiles=/usr/local/share/applications/com.fyralabs.Readymade.desktop
ExcludeFiles=/usr/lib/systemd/user/luminusos-readymade.service
ExcludeFiles=/usr/lib/systemd/user/gnome-session@live-installer.target.d/live-installer.session.conf
ExcludeFiles=/usr/share/gnome-shell/modes/live-installer.json
ExcludeFiles=/usr/share/gnome-session/sessions/live-installer.session
ExcludeFiles=/usr/share/wayland-sessions/live-installer.desktop
ExcludeFiles=/home/liveuser
ExcludeFiles=/var/home/liveuser
ExcludeFiles=/var/lib/AccountsService/users/liveuser
ExcludeFiles=/var/lib/AccountsService/icons/liveuser
