#!/usr/bin/env bash
set -uexo pipefail

# Common base packages shared across all editions

# Copy static files into the image
if [ -d files ]; then
  find files -mindepth 1 -maxdepth 1 -exec cp -arfT {} / \;
fi

dnf -y install \
  NetworkManager \
  systemd-udev
