#!/usr/bin/env bash
set -uexo pipefail

# Clean up after each build layer to keep image size down

dnf clean all
rm -rf /tmp/* || true
if command -v ostree &>/dev/null; then
  ostree container commit
fi
